### PR TITLE
feat(all): use PostgreSQL

### LINKED ISSUE #3: feat(): migrate to PostgreSQL

### PR DESCRIPTION
**Pull request by stonewallstan**
Closes #3

### CODE REVIEW

**Comment by mianuddin** [comment]
* @stonewallstan assign yourself to the PR
* you're missing a scope for the changes

**Comment by mianuddin** [comment]
Also, for future reference, add the reviewers once the PR is ready for review. Github should notify them.

**Comment by mianuddin** [comment]
So there are no new steps in terms of using `requirements.txt` or `PostgreSQL`?

**Comment by stonewallstan** [comment]
I believe there are no new changes since I made requirements.txt after I implemented the PostgreSQL db and I included the package for PostgreSQL in the contributing.md before I implemented the PostgresSQL. So everything in those two docs should be good to go.

**Comment by mianuddin** [comment]
@stonewallstan heads-up this PR has same `resume` discrepancy as the other PR

**Comment by mianuddin** [comment]
I tried running through your contributing guide and added some comments about places that needed improvement: https://github.com/slohacks/attendee-application-back-end/commit/9e6016cb7bdda217e1711053c4998a2b04fd3a56

Additionally, I was unable to successfully get django running from this branch:
screen shot 2018-09-11 at 20 47 32

**Pull request merged**
